### ISSUE TITLE
Connect to honey error

### ISSUE THREAD

**Issue by donot-wong** [ohmyadd/wetland#1]
when I start a container, i try to connect to it, but always return 
ssh_exchange_identification: Connection closed by remote host
I my log, record a ip who connect me, but in this ip dir, no file

**Comment by ohmyadd** [comment]
emm maybe you should check 'enable'' in [network] section of wetland.cfg.
if it is true, you should make sure wetland has root permissions to create a dummy interface and use iptables
And could you talk more about your test environment

**Comment by donot-wong** [comment]
really thank you response me so quickly, yes, the network->enable=true, and i use docker pull images from hub in my vps,and 
docker run -d --name sshd -p 22:22 -v ~/wetland.cfg:/root/wetland/wetland.cfg -v /tmp/logs:/root/wetland/log to create a container. 
and how I can ensure wetland has root permissions to create a dummy interface and use iptables?

**Comment by ohmyadd** [comment]
ok, if you run wetland without docker, just run it in root, and
if you run it in docker, you should see advanced network section in document of dockerhub
the doc means wetland container needs enough permissions to setup host vps's network
when create container , add `--cap-add NET_ADMIN --cap-add NET_RAW --net host`
and at lat if you can see interface named wdxxx, it works
